### PR TITLE
CIV-1130 Redis changes for claimant response  and claim creation

### PR DESCRIPTION
**Pull request by jeswanth-hmcts**
**Before creating a pull request make sure that:**

### JIRA link ###
https://tools.hmcts.net/jira/browse/CIV-11130

### Change description ###

Redis changes for claimant response  and claim creation

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by kenneth-hmcts — DISMISSED** [review]

**Review by neeta-hmcts — DISMISSED** [review]

**Review by jarekPierchala — APPROVED** [review]

**Review by neeta-hmcts — DISMISSED** [review]

**Review by kenneth-hmcts — DISMISSED** [review]

**Review by laarmada — CHANGES_REQUESTED** [review]
I have a important doubt about that:

export function generateRedisKey(req: AppRequest) {
  return req.params.id + req.session.user?.id;
}

**Review by laarmada — COMMENTED** [review]
I cant approve this PR

**Comment by jeswanth-hmcts** [comment]
> I have a important doubt about that:
> 
> export function generateRedisKey(req: AppRequest) { return req.params.id + req.session.user?.id; }




> I have a important doubt about that:
> 
> export function generateRedisKey(req: AppRequest) { return req.params.id + req.session.user?.id; } we will lose the data if for example we access now from mobile and later from computer, the session id will be different and we will have a missing data or duplicating data in redis which one is the valid???? the last session id but we will remain the information loosed in redis..... on the other hand we have the session in the cookies and also the claim id...... so .... I don't like this trick....


Correct, every time a new session ID is created when the session expires or the user logout , will lose the data from Redis, but this technical discussion already happened  with Sampan when Kadir started the ITHC ticket before implementing the changes, these changes were already implemented for release 1

**Comment by jeswanth-hmcts** [comment]
> we are saving that when some error happend: image



Could you explain with a complete example?

**Review by laarmada — CHANGES_REQUESTED** [review]
reset the status

**Review by laarmada — DISMISSED** [review]

**Review by dharmendrak — DISMISSED** [review]

**Review by neeta-hmcts — DISMISSED** [review]

**Review by jarekPierchala — DISMISSED** [review]

**Review by kenneth-hmcts — APPROVED** [review]

**Review by neeta-hmcts — APPROVED** [review]

**Pull request merged**
