### PR TITLE
Upgrade nested dependencies ajv and follow-redirects

### PR DESCRIPTION
**Pull request by taomoh**
### JIRA link ###

N/A

### Change description ###

Upgrade nested dependencies ajv and follow-redirects to fix vulnerabities

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Review by LeonardoPalmeiro — APPROVED** [review]
I will approve it 
we should avoid to use resolution .

**Review by TatsyMaslova — APPROVED** [review]

**Comment by osheaf01** [comment]
LGTM

**Comment by taomoh** [comment]
> I will approve it we should avoid to use resolution .

As discussed off this PR, we should have a separate ticket to attempt removing problematic direct dependencies. Please note that sass-lint is used in the yarn lint target, which originated from expressjs-template

**Review by osheaf01 — COMMENTED** [review]
LGTM

**Pull request merged**
