### PR TITLE
CIV-15770  preferred court location question

### PR DESCRIPTION
**Pull request by LeonardoPalmeiro**
### JIRA link ###

https://tools.hmcts.net/jira/browse/CIV-15770

### Change description ###
image

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by paul-pearson — DISMISSED** [review]
There's a small typo in key EXPlANATION (lower case L).  Approved as this wasn't added in this PR but you might want to correct it.

**Review by neeta-hmcts — COMMENTED** [review]
I believe we will need civil-service changes too here to update DQ document with the updated logic.

**Comment by LeonardoPalmeiro** [comment]
> There's a small typo in key EXPlANATION (lower case L). Approved as this wasn't added in this PR but you might want to correct it.

Thank you Paul. we can open another ticket for it if you don't mind

**Comment by LeonardoPalmeiro** [comment]
> I believe we will need civil-service changes too here to update DQ document with the updated logic.

I will talk with you about it.

**Review by neeta-hmcts — APPROVED** [review]

**Review by neeta-hmcts — DISMISSED** [review]

**Review by paul-pearson — DISMISSED** [review]

**Review by LTurkingtonHMCTS — APPROVED** [review]

**Pull request merged**
